basePath: /
definitions:
  models.Appointment:
    properties:
      apptDate:
        type: string
      apptDesc:
        type: string
      apptName:
        type: string
      apptTime:
        type: string
      apptType:
        type: string
      id:
        type: integer
      userID:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is an API for managing appointments.
  title: Appointments API
  version: "1.0"
paths:
  /:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Appointment'
            type: array
      summary: List appointments
swagger: "2.0"
